package service

// MethodDescription is returned by rpc.discover so shell tools and bots can
// inspect the local API without scraping documentation.
type MethodDescription struct {
	Name     string         `json:"name"`
	Summary  string         `json:"summary"`
	Mutating bool           `json:"mutating"`
	Params   map[string]any `json:"params_example"`
}

func method(name, summary string, mutating bool, params map[string]any) MethodDescription {
	if params == nil {
		params = map[string]any{}
	}
	return MethodDescription{Name: name, Summary: summary, Mutating: mutating, Params: params}
}

var apiMethods = []MethodDescription{
	method("messages.on_date", "Find the first locally stored message within a calendar day", false, map[string]any{"chat_jid": "123@lid", "start": 1789084800000, "end": 1789171200000}),
	method("poll.info", "Read locally received poll options and vote totals", false, map[string]any{"chat_jid": "123@g.us", "message_id": "ABC"}),
	method("poll.create", "Create a poll with 2–12 distinct options", true, map[string]any{"chat_jid": "123@g.us", "question": "When?", "options": []string{"Today", "Tomorrow"}, "multiple": false}),
	method("poll.vote", "Replace your poll selections; an empty list retracts your vote", true, map[string]any{"chat_jid": "123@g.us", "message_id": "ABC", "options": []string{"Today"}}),
	method("event.info", "Read locally received event details; RSVP is unavailable", false, map[string]any{"chat_jid": "123@g.us", "message_id": "ABC"}),
	method("group.invite_preview", "Read group identity before joining; does not join", false, map[string]any{"link": "https://chat.whatsapp.com/INVITE_CODE"}),
	method("group.join_previewed", "Join only after rechecking the previewed identity; joined=false means membership is not confirmed", true, map[string]any{"link": "https://chat.whatsapp.com/INVITE_CODE", "expected_jid": "123@g.us"}),
	method("group.invite_qr", "Return the current invite link and PNG data URI", false, map[string]any{"chat_jid": "123@g.us"}),
	method("community.info", "Read description, linked groups and groups available to link", false, map[string]any{"chat_jid": "123@g.us"}),
	method("community.description", "Change description after fresh admin and previous-value checks", true, map[string]any{"chat_jid": "123@g.us", "description": "New description", "previous": "Old description"}),
	method("community.link", "Link or unlink a group after checking current permissions", true, map[string]any{"chat_jid": "123@g.us", "child_jid": "456@g.us", "action": "link"}),
	method("status.audience_contacts", "Resolve included/excluded status audience contacts; read-only", false, nil),
	method("rpc.discover", "List protocol methods and event names", false, nil),
	method("status.get", "Get connection and login state", false, nil),
	method("update.status", "Report the installed version and any newer release", false, nil),
	method("update.check", "Ask GitHub now whether a newer release exists", false, nil),
	method("update.download", "Download and check this platform's artifact for the newer release", true, nil),
	method("bugreport.environment", "Describe what a bug report would disclose", false, nil),
	method("bugreport.submit", "Send a report to the whatsappgo project in Jabali Bugs Intake", true,
		map[string]any{"subject": "Videos play as a black screen", "body": "Steps to reproduce..."}),
	method("connection.connect", "Connect the linked device", true, nil),
	method("connection.disconnect", "Disconnect without unlinking", true, nil),
	method("pairing.start", "Start QR-code pairing", true, nil),
	method("pairing.phone", "Request a phone pairing code", true, map[string]any{"phone": "15551234567"}),
	method("account.logout", "Unlink this profile and delete its device session", true, nil),
	method("chats.list", "List or search chats", false, map[string]any{"limit": 100, "offset": 0, "query": "", "archived": false}),
	method("chats.archived_count", "Count archived chats", false, nil),
	method("chats.unread_count", "Count unread messages in visible chats", false, nil),
	method("chat.info", "Get contact metadata and shared-content counts", false, map[string]any{"chat_jid": "123@lid"}),
	method("chat.shared", "Page through a chat's media, documents, or links", false, map[string]any{"chat_jid": "123@lid", "category": "media", "offset": 0, "limit": 60}),
	method("chat.pin", "Pin or unpin a chat", true, map[string]any{"chat_jid": "123@lid", "value": true}),
	method("chat.mute", "Mute or unmute a chat; duration_seconds 0 mutes until undone", true, map[string]any{"chat_jid": "123@lid", "value": true, "duration_seconds": 28800}),
	method("media.shared", "Page media, documents or links across every chat", false, map[string]any{"category": "media", "offset": 0, "limit": 60}),
	method("sticker.send", "Reuse an original sticker from this account's history", true, map[string]any{"chat_jid": "123@lid", "message_id": "ABC", "to_chat_jid": "456@lid", "reply_to": ""}),
	method("chats.mark_all_read", "Clear the unread state of every conversation", true, nil),
	method("labels.list", "List the account's chat lists", false, nil),
	method("label.create", "Create a chat list", true, map[string]any{"name": "Work", "color": 0}),
	method("chat.label", "Add a chat to a list or remove it", true, map[string]any{"chat_jid": "123@lid", "label_id": "1", "value": true}),
	method("chat.labels", "List the lists a chat belongs to", false, map[string]any{"chat_jid": "123@lid"}),
	method("contact.block", "Block or unblock a contact", true, map[string]any{"chat_jid": "123@s.whatsapp.net", "value": true}),
	method("contacts.blocked", "List blocked contacts", false, nil),
	method("group.create", "Create a group with the given name and participants", true, map[string]any{"name": "Team", "participants": []string{"123@s.whatsapp.net"}}),
	method("group.info", "Fetch live group membership, roles, permissions and creation metadata", false, map[string]any{"chat_jid": "123@g.us"}),
	method("group.requests.list", "List pending group join requests (current admins only)", false, map[string]any{"chat_jid": "123@g.us"}),
	method("group.set_photo", "Set or remove a group photo after fresh edit-permission validation", true, map[string]any{"chat_jid": "123@g.us", "path": "/tmp/prepared-group-photo.jpg", "remove": false}),
	method("group.requests.review", "Approve or reject one still-pending group request after fresh admin validation", true, map[string]any{"chat_jid": "123@g.us", "participant": "456@lid", "requested_at": 1788990000000, "action": "approve"}),
	method("group.set_info", "Update group name or description after checking permissions and the previous value", true, map[string]any{"chat_jid": "123@g.us", "field": "name", "value": "New group name", "previous": "Old group name"}),
	method("group.set_permission", "Update one group permission after checking current admin rights; boolean value and previous are required", true, map[string]any{"chat_jid": "123@g.us", "field": "send_messages", "value": false, "previous": true}),
	method("group.invite_link", "Get the group invite link; reset revokes the previous link (admins only)", true, map[string]any{"chat_jid": "123@g.us", "reset": false}),
	method("group.members", "Add, remove, promote or demote group members with permission checks", true, map[string]any{"chat_jid": "123@g.us", "action": "add", "participants": []string{"123@s.whatsapp.net"}}),
	method("group.leave", "Leave a group without deleting local history", true, map[string]any{"chat_jid": "123@g.us"}),
	method("chat.delete", "Delete a chat on every linked device and locally", true, map[string]any{"chat_jid": "123@lid"}),
	method("chat.clear", "Empty a conversation on every device without removing it", false, map[string]any{"chat_jid": "1234567890@s.whatsapp.net"}),
	method("chat.disappearing", "Set the disappearing-message timer for a chat, in seconds (0 turns it off)", false, map[string]any{"chat_jid": "1234567890@s.whatsapp.net", "duration_seconds": 604800}),
	method("chat.export", "Write a conversation to a text file", false, map[string]any{"chat_jid": "1234567890@s.whatsapp.net", "path": "/home/user/chat.txt", "replace": false}),
	method("channel.create", "Create a channel", true, map[string]any{"name": "My channel", "description": ""}),
	method("channel.follow_link", "Follow a channel from its invite link", true, map[string]any{"link": "https://whatsapp.com/channel/CODE"}),
	method("community.create", "Create a community", true, map[string]any{"name": "My community"}),
	method("group.join_link", "Join a group from its invite link", true, map[string]any{"link": "https://chat.whatsapp.com/CODE"}),
	method("channel.follow", "Follow or leave a channel", true, map[string]any{"jid": "123@newsletter", "value": true}),
	method("channel.mute", "Mute or unmute a channel", true, map[string]any{"jid": "123@newsletter", "value": true}),
	method("status.post", "Publish a status update, as text or as a photo or video", true, map[string]any{"text": "Hello", "background": 0}),
	method("privacy.get", "Read the account's privacy settings", false, map[string]any{}),
	method("profile.get", "Read your WhatsApp name, About text and profile photo", false, map[string]any{}),
	method("status.audience", "Read the default status broadcast audience and exception JIDs", false, map[string]any{}),
	method("privacy.default_timer.set", "Set the default timer for new chats; current value cannot be read", true, map[string]any{"seconds": 86400}),
	method("notifications.get", "Read local per-profile notification preferences", false, map[string]any{}),
	method("notifications.set", "Change a local notification preference", true, map[string]any{"name": "previews", "value": false}),
	method("notifications.test_sound", "Preview the incoming or outgoing desktop sound (Linux)", true, map[string]any{"kind": "incoming"}),
	method("preferences.get", "Read local media-download and link-preview preferences", false, map[string]any{}),
	method("preferences.set", "Change one local network preference", true, map[string]any{"name": "download_video", "value": false}),
	method("privacy.set", "Change one privacy setting", true, map[string]any{"name": "last_seen", "value": "contacts"}),
	method("profile.set_about", "Change the account's about text", true, map[string]any{"text": "At the keyboard"}),
	method("profile.set_name", "Change the WhatsApp profile name (1–25 characters)", true, map[string]any{"name": "New name"}),
	method("profile.set_photo", "Set your account photo from a 640×640 JPEG, or explicitly remove it", true, map[string]any{"path": "/path/to/prepared-photo.jpg", "remove": false}),
	method("chat.favorite", "Add or remove a chat from Favorites", false, map[string]any{"chat_jid": "1234567890@s.whatsapp.net", "value": true}),
	method("chat.archive", "Archive or restore a chat", true, map[string]any{"chat_jid": "123@lid", "value": true}),
	method("chat.set_read", "Mark a chat read or unread across linked devices", true, map[string]any{"chat_jid": "123@lid", "value": true}),
	method("chat.read", "Send receipts and clear the local unread count", true, map[string]any{"chat_jid": "123@lid", "sender_jid": "456@lid", "message_ids": []string{"MESSAGE_ID"}, "timestamp": 0}),
	method("chat.typing", "Set composing or paused presence", true, map[string]any{"chat_jid": "123@lid", "typing": true}),
	method("contact.presence.subscribe", "Subscribe to a contact's online and last-seen updates", true, map[string]any{"chat_jid": "123@lid"}),
	method("chat.avatar", "Fetch and cache a chat avatar", true, map[string]any{"chat_jid": "123@lid", "refresh": false}),
	method("statuses.list", "List active status stories grouped by sender", false, nil),
	method("calls.list", "List synchronized call records", false, nil),
	method("channels.list", "List followed channels", false, nil),
	method("communities.list", "List joined communities", false, nil),
	method("messages.list", "Page through one chat's messages", false, map[string]any{"chat_jid": "123@lid", "before": 0, "limit": 50}),
	method("messages.search", "Search local message text", false, map[string]any{"query": "invoice", "limit": 50}),
	method("link.preview", "Resolve Open Graph metadata for composer text", false, map[string]any{"text": "https://example.com"}),
	method("link.preview.refresh", "Replace a small cached link image with its full preview", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID"}),
	method("history.request", "Request an older history page", true, map[string]any{"chat_jid": "123@lid", "limit": 50}),
	method("history.refresh", "Request a recent history page", true, map[string]any{"chat_jid": "123@lid", "limit": 50}),
	method("message.get", "One stored message with its reactions and quoted line", false, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID"}),
	method("message.download", "Download and cache message media", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID"}),
	method("message.played", "Mark an incoming voice or video message as played", true, map[string]any{"chat_jid": "123@lid", "sender_jid": "456@lid", "message_id": "MESSAGE_ID", "timestamp": 0}),
	method("message.send", "Send a text message", true, map[string]any{"chat_jid": "123@lid", "text": "Hello", "reply_to": "", "reply_chat_jid": "", "link_preview": map[string]any{}}),
	method("contacts.shareable", "Search up to 100 local contacts with known phone numbers, including archived chats", false, map[string]any{"query": "Alice"}),
	method("message.send_contact", "Send one reviewed name and international phone number as a contact card", true, map[string]any{"chat_jid": "123@lid", "reply_to": "", "contact": map[string]any{"name": "Alice", "phone": "+15551234567"}}),
	method("message.send_media", "Send media; document=true preserves file semantics regardless of MIME type", true, map[string]any{"chat_jid": "123@lid", "path": "/absolute/file", "caption": "", "reply_to": "", "voice": false, "document": false}),
	method("message.react", "Add or remove a reaction", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "sender_jid": "", "emoji": "👍"}),
	method("message.pin", "Pin a message for 24 hours, 7 days, or 30 days", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "sender_jid": "", "duration_seconds": 604800}),
	method("message.unpin", "Remove the pinned message from a chat", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "sender_jid": ""}),
	method("message.star", "Star or unstar a message for the account", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "sender_jid": "", "from_me": false, "starred": true}),
	method("messages.starred", "List starred messages, optionally scoped to chat_jid", false, map[string]any{"limit": 50, "chat_jid": ""}),
	method("message.forward", "Forward a message into another conversation", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "to_chat_jid": "456@lid"}),
	method("message.edit", "Edit a sent text message", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "text": "Corrected"}),
	method("message.delete", "Delete a message for everyone", true, map[string]any{"chat_jid": "123@lid", "message_id": "MESSAGE_ID", "sender_jid": ""}),
	method("contact.resolve", "Resolve a phone number to a WhatsApp chat", true, map[string]any{"phone": "15551234567"}),
	method("contact.save", "Resolve a phone number and save a local WhatsAppGo label", true, map[string]any{"phone": "15551234567", "name": "Alice"}),
}

var apiEvents = []string{
	"poll.updated", "community.updated",
	"call.upsert", "calls.synced", "chat.presence", "chat.updated", "group.updated",
	"connection.changed", "contact.presence", "daemon.error", "directory.synced",
	"history.collected", "history.synced", "media.collected", "message.edited",
	"message.pinned", "message.reaction", "message.receipt", "message.revoked", "message.upsert",
	"notification.received", "notifications.updated", "preferences.updated", "privacy.changed", "pairing.error", "pairing.qr", "pairing.state",
	"pairing.success", "update.available", "update.progress", "update.ready",
	"update.failed",
}

func discoveryResult() map[string]any {
	return map[string]any{
		"protocol_version": 1,
		"transport":        "newline-delimited JSON over an owner-only Unix socket",
		"methods":          apiMethods,
		"events":           apiEvents,
	}
}
